### PR TITLE
Refactor theme-cart to remove jQuery and add tests

### PR DESCRIPTION
**Pull request by t-kelly**
Removes jQuery from theme-cart and uses Fetch API instead. Requires a Fetch and Promise Polyfill for IE11.

Still todo
- [ ] Add localStorage functionality to manage cart across multiple tabs
- [ ] Docs in README

### CODE REVIEW

**Comment by jonathanmoore** [comment]
As a heads up, this approach might not be compatible with the highly used Facebook Pixels.  Here is a quote from another theme developer on the issues they ran into with fetch.

> Also, I just wanted to warn everyone about the usage of fetch API (that aims to replace the old school XMLHttpRequest and all its quirkcs). It appears that adding to cart using the fetch API is incompatible with the current Facebook Pixel integration. After a lot of testing on my end I was forced to revert using XMLHttpRequest which is the only one that is “catched” by the Facebook Pixel.

I'm unsure if this is a direct result of the Facebook API itself or more than likely Shopify's implementation through the trekkie functionality.  If it comes back to trekkie then it probably impacts the Google Analytics integration as well.

**Comment by t-kelly** [comment]
Did some digging into this. @bakura10 you are right that we are only listening for XHR requests that match Cart API requests and then triggering a Trekkie event for FB Pixel. Going to see if I can expand this logic to include Fetch.

**Comment by bakura10** [comment]
Thanks for confirming this. It would be awesome :).

**Comment by t-kelly** [comment]
Have a PR open in core to fix the issue with Trekkie not listening to Fetch requests to cart API. Once that is merged, this can move forward.

**Comment by dan-gamble** [comment]
I seem to keep getting an error when attempting to use this. I've just straight copied everything to my local project so i can test it.

The error i'm getting is: img

Doing 2 very simple calls with Preact

```javascript
  async onRemoveClick () {
    const data = await removeItem(this.props.item.key)
    console.log(data)
  }

  async updateQuantity (quantity) {
    const data = await updateItem(this.props.item.key, { quantity })
    console.log(data)
  }
```

Both give the same error. Could this be anything to do with the browserSync `:3000` vs using the shop URL or is the `fetch` problem outlined above?

**Comment by t-kelly** [comment]
@dan-gamble good timing -- I've been working on it all day. Almost ready! Will open again in a new PR when it is.

**Pull request closed without merging**
