### PR TITLE
@shopify/theme-cart: v1.0.0

### PR DESCRIPTION
**Pull request by t-kelly**
Followup to https://github.com/Shopify/theme-scripts/pull/31

Major overhaul from first attempt. Gave everything a very thorough review and test. New docs should explain everything. 

**Fetch requests now mimic XHR behaviour and trigger the appropriate Trekkie requests so Facebook Pixels are 💯**

Easiest way to test it is to:
1. `yarn link` it to your theme project
2. `import * as cart from '@shopify/theme-cart'`
3. `window.cart = cart;`
4. Open Chrome console and type `await cart.getState();`
5. Bravo async results in your console

cc @jonathanmoore, @bakura10, @dan-gamble, @gavinballard

### CODE REVIEW

**Comment by bakura10** [comment]
Hey !

I've just tried and fetch still does not trigger trekkie event here. Here is my code:

```js
const formElement = this.element.querySelector('form[action^="/cart/add"]'),
      formData = new FormData(formElement);

    fetch('/cart/add.js', {
      credentials: 'same-origin',
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'X-Requested-With': 'XMLHttpRequest' // This is needed as currently there is a bug in Shopify that assumes this header
      },
      body: formData
    }).then((response) => {
      // ...
      }
    });
```

Can you please tell me what I'm doing wrong?

**Comment by t-kelly** [comment]
@bakura10 you scared me. I was just testing it and noticed that it does not fire if you're trying from localhost, but it does fire if you're trying from your `myshopify.com` URL.

**Comment by t-kelly** [comment]
Scratch that -- it works on both for me 🤔

**Comment by bakura10** [comment]
It’s definitely not firing on my end on myshopify.com domain. I’ll try again later today and send you my demo store :)

**Comment by dan-gamble** [comment]
Awesome, will give this a test drive today and report back on my trekkie findings

**Comment by dan-gamble** [comment]
To add to this, one thing i'm finding is with code like:

```javascript
  async updateQuantityOfItem (quantity, item) {
    await window.cart.updateItem(item.key, { quantity })
    const state = await window.cart.getState()

    this.updateCart(state)
  }
```

I'm getting: img

Would it be possible to pass `line` to things like `updateItem()` so we could bypass the first `cart.js` request that happens? Just thinking if we can pass the line then we don't need that extra request and most of the time we can pass the line. If for some reason the line can't be passed we could fall back to `key` way of getting things which would cost that extra request. Unless i'm missing something as to why the `key` way is the better way to go, i know it would be better for integrity which may well be the answer as to why it's there!

**Comment by dan-gamble** [comment]
RE: Facebook pixel, i'm just using a vanilla setup, i'm guessing i probably need to do some Facebook pixel integration first?

**Comment by t-kelly** [comment]
> I guess allowing both is not unreasonable?

Actually I'm going to hold off on this... it's a non breaking change so it change be added with a future minor update

**Comment by dan-gamble** [comment]
Returning the cart instead of the singular object makes more sense to me. I was debating about whether having to get it all again or start having to calculate things like subtotal internally to prevent the extra call.

**Comment by jonathanmoore** [comment]
Was `cookiesEnabled` intentionally removed from theme-cart with this PR or was it overlooked?  Related #52 

If it was accidentally removed, I'm happy to open a PR to add it back in or otherwise open a PR to come up for an alternate approach for starter-theme https://github.com/Shopify/starter-theme/blob/master/src/scripts/layout/theme.js#L19

**Comment by NathanPJF** [comment]
@jonathanmoore Wasn't removed intentionally 😨 A PR would be very much welcome :)

**Comment by t-kelly** [comment]
I did not include it because it is not directly related to the cart. Checking for cookies can be done for a wide number of reasons. Also it is pretty straight forward so I would advocate just writing it out straight or in your own projects utils file.

**Pull request merged**
